# Generated by Django 2.2.4 on 2019-08-03 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_nationality'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costcenter_code', models.CharField(max_length=200, verbose_name='Costcenter Code')),
                ('financeproject_code', models.CharField(max_length=200, verbose_name='Financeproject Code')),
                ('expensecode_number', models.CharField(max_length=100, verbose_name='Expensecode Number')),
                ('costcenter_name', models.CharField(max_length=200, verbose_name='Costcenter Name')),
                ('financeproject_name', models.CharField(max_length=200, verbose_name='Financeproject Name')),
                ('expensecode_type', models.CharField(max_length=100, verbose_name='Expensecode Type')),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Budgeted amount')),
                ('budget_year', models.IntegerField(blank=True, null=True, verbose_name='Year')),
                ('orders_amount', models.IntegerField(blank=True, null=True, verbose_name='Orders amount')),
            ],
            options={
                'verbose_name': 'Group Budget Report',
                'verbose_name_plural': 'Group Budget Reports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetDoc',
            fields=[
                ('budgetdoc_id', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('year', models.IntegerField(verbose_name='Year')),
            ],
            options={
                'verbose_name': 'Budget Document',
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('costcenter_id', models.AutoField(primary_key=True, serialize=False)),
                ('costcenter_name', models.CharField(max_length=200, verbose_name='Name')),
                ('costcenter_code', models.CharField(max_length=200, verbose_name='Code')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Finance Cost Center',
                'verbose_name_plural': 'Finance Cost Centers',
                'ordering': ['costcenter_code'],
            },
        ),
        migrations.CreateModel(
            name='FinancingAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Financing agency',
                'verbose_name_plural': 'Financing agencies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Grant',
                'verbose_name_plural': 'Grants',
            },
        ),
        migrations.CreateModel(
            name='Grantdomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=200, verbose_name='Grant domain')),
            ],
            options={
                'verbose_name': 'Grant domain',
                'verbose_name_plural': 'Grant domains',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('financeproject_id', models.AutoField(primary_key=True, serialize=False)),
                ('financeproject_name', models.CharField(max_length=200, verbose_name='Name')),
                ('financeproject_code', models.CharField(max_length=200, unique=True, verbose_name='Code')),
                ('financeproject_startdate', models.DateField(blank=True, null=True, verbose_name='Starting date')),
                ('financeproject_enddate', models.DateField(blank=True, null=True, verbose_name='Ending date')),
                ('financeproject_totalamount', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Total amount')),
                ('financeproject_overheads', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Overhead')),
                ('financeproject_funding', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Funding')),
                ('financeproject_responsible', models.CharField(max_length=200, verbose_name='Responsible')),
                ('costcenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.CostCenter', verbose_name='Cost Center')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Currency', verbose_name='Currency')),
                ('grant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.Grant', verbose_name='Grant')),
            ],
            options={
                'verbose_name': 'Finance Project',
                'verbose_name_plural': 'Finance Projects',
                'ordering': ['financeproject_code', 'costcenter'],
            },
        ),
        migrations.AddField(
            model_name='grant',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Grantdomain', verbose_name='Grant domain'),
        ),
        migrations.AddField(
            model_name='grant',
            name='grantor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.FinancingAgency', verbose_name='Grantor'),
        ),
        migrations.AddField(
            model_name='grant',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Nationality', verbose_name='Grant nationality'),
        ),
        migrations.CreateModel(
            name='ExpenseCode',
            fields=[
                ('expensecode_id', models.AutoField(primary_key=True, serialize=False)),
                ('expensecode_number', models.CharField(max_length=100, verbose_name='ExpenseCode Number')),
                ('expensecode_type', models.CharField(max_length=100, verbose_name='ExpenseCode Type')),
                ('financeproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.Project', verbose_name='Finance Project')),
            ],
            options={
                'verbose_name': 'Expense Code',
                'verbose_name_plural': 'Expense Codes',
                'unique_together': {('expensecode_number', 'financeproject')},
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('budget_id', models.AutoField(primary_key=True, serialize=False)),
                ('budget_amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Amount (NET)')),
                ('budget_year', models.IntegerField(blank=True, null=True, verbose_name='Year')),
                ('expensecode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.ExpenseCode', verbose_name='Expense Code')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'unique_together': {('budget_year', 'expensecode')},
            },
        ),
    ]
